spring.application.name=MiniProjet_SpringBoot
spring.datasource.url=jdbc:mysql://localhost:3306/flotte_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081